/**
 * Extend the Cloudflare Env interface with our D1, R2, and secret bindings.
 * The base Env is auto-generated by `wrangler types` in worker-configuration.d.ts.
 */
declare interface Env {
	// D1 Database
	DB: D1Database;

	// R2 Bucket for images/assets
	ASSETS_BUCKET: R2Bucket;

	// Salesforce OAuth credentials (set via `wrangler secret put`)
	SF_CLIENT_ID: string;
	SF_CLIENT_SECRET: string;
	SF_INSTANCE_URL: string;

	// Existing vars
	VALUE_FROM_CLOUDFLARE: string;
}
